# Generated by Django 4.1.3 on 2022-11-30 13:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searching_for', models.CharField(max_length=255, verbose_name='post')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('contract', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage')], default=('CDI', 'CDI'), max_length=10, verbose_name='type_de_contact')),
                ('post_number', models.PositiveIntegerField(default=1)),
                ('description', ckeditor.fields.RichTextField()),
                ('looking_for', ckeditor.fields.RichTextField()),
                ('experience', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'offers',
            },
        ),
    ]
